Setup
danmainah/vacations-booking-front-end pull request #1
Opened 2021-11-11 18:04 UTC by danmainah

**In this milestone I did the following**

- Created a react app 
- Added dependencies
- Added linters

2021-11-12 09:15 UTC, themonster2015 approved these changes
Hi @danmainah Good job. Your code looks good to me 👍

2021-11-12 09:46 UTC, ShinobiWarior requested changes
**Hi @danmainah ,**

### Changes requested 🚫 🚫 🚫 
Great job so far. However, there are still some small things to be improved.

1. Please remove all unnecessary files like: 
- public/logo192.png
- public/logo512.png
- public/robots.txt
- src/reportWebVitals.js
- src/setupTests.js

2. Please create a new branch on the Rails backend project and update the readme file by adding text:
  ```
Front-end project progress:
 - React app created
```
Create a pull request for this new branch on the back-end project side and add a link to this pull request.

Cheers 🥂 and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2021-11-15 07:47 UTC, igorkol91 approved these changes
Looks great. Good job!!

2021-11-15 08:09 UTC, ShinobiWarior approved these changes

2021-11-15 08:10 UTC, merged